export default [
    "Your next deploy will be bug-free. Mostly.",
    "A coffee in hand is worth two in the pot.",
    "Syntax error? More like a happy little accident.",
    "An old friend will send you a meme today. Cherish it.",
    "You will find a clever solution in fewer lines of code.",
    "Take a break before the code takes a break for you.",
    "Your semicolon is in the right place this time.",
    "The answer is in the console. Always check the console.",
    "Sometimes, the best refactor is no refactor.",
    "Someone admires your tab discipline.",
    "A random act of kindness will ripple for weeks.",
    "That unread book is finally ready for you.",
    "Beware of off-by-one errors… and vague requirements.",
    "A rubber duck will help you debug today.",
    "Trust your intuition—it's better than autocomplete.",
    "The best commit message is the one that tells the truth.",
    "A long walk will solve the problem your code can't.",
    "Eat the last cookie. You've earned it.",
    "Tomorrow brings clarity and better naming conventions.",
    "A hotfix is only “temporary” if you delete it someday.",
    "Don't ignore the README. It has feelings too.",
    "A forgotten idea will return when you least expect it.",
    "You are someone's Stack Overflow hero.",
    "Dream in functions. Wake up with solutions.",
    "A passing thought today holds a million-dollar idea.",
    "Light mode or dark mode—both lead to bugs.",
    "There's elegance in simplicity. Your code agrees.",
    "You will soon laugh at a problem you once feared.",
    "The next sprint will feel like a stroll.",
    "You'll fix a bug today that wasn't yours… and feel proud.",
    "Eat more fiber. Also, write more tests.",
    "Your next PR will be approved without comment.",
    "Someone's still trying to figure out your clever hack.",
    "Avoid premature optimization—and rushed decisions.",
    "You'll find joy in deleting code this week.",
    "You're two commits away from greatness.",
    "Soon, you'll find the right emoji for your mood.",
    "Don't name your variables after exes.",
    "It works on my machine” will no longer be your truth.",
    "A kind word today will open a surprising door tomorrow.",
    "You're not stuck—you're just buffering.",
    "Good code is like a good joke: if you have to explain it...",
    "The best ideas often begin with “what if…”",
    "Let your curiosity break the loop.",
    "You'll soon learn something new that feels oddly familiar.",
    "Don't sleep on the power of sleep.",
    "Read the diff before you merge. Then celebrate.",
    "Your weirdest idea will be your most appreciated.",
    "The weekend will come faster than you think.",
    "You're not lost. You're in a recursive thought.",
    "Your build will pass while you're making toast.",
    "Every great developer was once a beginner with bad CSS.",
    "A sarcastic comment today will spark a real connection.",
    "Auto-formatting is your friend. Mostly.",
    "Step away from the screen. Come back enlightened.",
    "Your future self will thank you for writing that doc.",
    "Someone will copy your clever solution and never tell you.",
    "Look up. Your answer might not be on GitHub.",
    "A great variable name will come to you in the shower.",
    "Your keyboard has typed more wisdom than you know.",
    "There is no “final_final_v2”. Only acceptance.",
    "Your next bug fix will teach you something unexpected.",
    "Beware of “just one more feature.”",
    "The best feature is the one you didn't build.",
    "You are the MVP—even if you're not in the MVP.",
    "Side projects need naps too.",
    "Laughter is the best error handler.",
    "You are running npm install in someone's dreams.",
    "You'll soon find joy in the terminal.",
    "Keep pushing… but not to main without review.",
    "Gratitude will change your day faster than caffeine.",
    "The solution you seek is simpler than you expect.",
    "Remember: you're allowed to not know everything.",
    "One clear line is worth ten clever ones.",
    "Your next job title is “Problem Whisperer.”",
    "Merge conflicts build character.",
    "Take pride in clean code—and clean dishes.",
    "Someone you help today will remember it for years.",
    "Comment like your future self has amnesia.",
    "“Temporary” code is just code that no one deletes.",
    "Happiness is a green test suite.",
    "You're not over-engineering. You're creatively detouring.",
    "Embrace boredom—it leads to breakthroughs.",
    "The linter is annoying because it cares.",
    "Your passion projects deserve your attention.",
    "That feature request? You don't have to say yes.",
    "Courage is committing without fear.",
    "Celebrate small wins. They're the building blocks.",
    "An unread Slack message is not an emergency.",
    "You are more than your job title.",
    "That “crazy” idea might be tomorrow's standard.",
    "Learn from bugs. Apologize to none.",
    "The biggest bottleneck is self-doubt.",
    "Refactor your habits like you refactor your code.",
    "Brackets close. Seasons change. You grow.",
    "Your backlog isn't a to-do list—it's a buffet.",
    "Ask the question. Even if it feels silly.",
    "Read your own code like it's someone else's.",
    "Don't ignore warnings—they're little nudges of love.",
    "You are not alone. Someone else has the same error."
]